### ISSUE TITLE
dlls/ntdll/unix/fsync.c:122:21: error: field 'type' has incomplete type

### ISSUE THREAD

**Issue by plaimbock** [Frogging-Family/wine-tkg-git#324]
Thank you for wine-tkg-git! On Fedora 34 with GCC11, wine-tkg-git 6.4.r0.g7ec998e1, wine-6.4, wine-staging v6.4 the build fails with:

 gcc -m64 -c -o dlls/ntdll/unix/loader.o dlls/ntdll/unix/loader.c -Idlls/ntdll -Iinclude -D__WINESRC__ -D_NTSYSTEM_ \
  -D_ACRTIMP= -DWINBASEAPI= -D_MSVCR_VER=0 -DBINDIR=\"/usr/bin\" -DDLL_TO_BINDIR=\"`./tools/makedep -R \
  /usr/lib64/wine /usr/bin`\" -DBIN_TO_DATADIR=\"`./tools/makedep -R /usr/bin /usr/share/wine`\" \
  -DWINE_UNIX_LIB -D_REENTRANT -fPIC -fasynchronous-unwind-tables -Wall -pipe -fcf-protection=none \
  -fno-stack-protector -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body \
  -Wignored-qualifiers -Winit-self -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes \
  -Wtype-limits -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -gdwarf-2 -gstrict-dwarf -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security  -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wno-error
dlls/ntdll/unix/fsync.c:122:21: error: field 'type' has incomplete type
  122 |     enum fsync_type type;
      |                     ^~~~
dlls/ntdll/unix/fsync.c:208:66: error: parameter 2 ('type') has incomplete type
  208 | static struct fsync *add_to_list( HANDLE handle, enum fsync_type type, void *shm )
      |                                                  ~~~~~~~~~~~~~~~~^~~~

Changes in customization.cfg:
_plain_version="wine-6.4"
_staging_version="v6.4"
_fsync_futex2="false"
_update_winevulkan="false"

Any idea what could be causing this? More output attached. Thanks!
[wine-6.4_gcc11_error.txt](https://github.com/Frogging-Family/wine-tkg-git/files/6287109/wine-6.4_gcc11_error.txt)

**Comment by Tk-Glitch** [comment]
Looks like wine will need yet another adaptation pass for GCC11, unless this isn't an issue anymore when GCC11 releases. I cannot reproduce the issue with GCC 10.2.0.

**Comment by gardotd426** [comment]
Just FYI, I was able to build 6.4 and 6.5 with GCC 11 on Arch. I just tried to build again, I got a different error, but I'm guessing it's related to wine being on 6.6 but wine-staging not being rebased yet. But yeah I definitely have built multiple builds with GCC 11.

**Comment by gardotd426** [comment]
Actually no, that's not it. It has indeed been rebased.

But I definitely have built with GCC 11. 

Here's the error:

```
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: dlls/mfreadwrite/reader.cross.o:reader.c:(.text+0x2f1d): undefined reference to `heap_alloc_zero'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make: *** [Makefile:117455: dlls/mfreadwrite/mfreadwrite.dll] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by gardotd426** [comment]
Okay, so I downgraded to GCC 10 on Arch and I got the exact same error, so it's not GCC related. But yeah, once that problem with the building gets fixed, I should be able to build with GCC 11 again, as like I've said, it worked fine on 6.5.

**Comment by Tk-Glitch** [comment]
Builds just fine here :shrug: broken gstreamer then?

**Comment by gardotd426** [comment]
How would one go about fixing that? My first thought was that it was a GCC 11 thing, but like I said downgrading to GCC 10.2.0-6 gave me the exact same error. I'm using the regular official Arch package for gstreamer, and the only community patch I'm using is the Origin Downloads one.

**Comment by Tk-Glitch** [comment]
ccache dir should be either in your $HOME dir or in $HOME/cache. For the gstreamer issue, your linker error seems to point to a problem with your glibc headers, since `heap_alloc_zero` is apparently define there.

**Comment by gardotd426** [comment]
Okay, .ccache dir is at ~/.ccache. Should I try using asp to pull in the glibc PKGBUILD and build it locally?

**Comment by plaimbock** [comment]
Solved after I cleaned all caches. Sorry for the noise. Feel free to close this issue at your convenience.

**Comment by gardotd426** [comment]
Weirdly, I have been unable to build the current versions no matter what I do, I've tried building glibc and mingw locally against GCC 11, I've tried reinstalling glibc and mingw from the repos after downgrading to GCC 10, nothing works, I get the same error every time. But when I specify `wine-6.5` for plain_version and `v6.5` for staging_version, the build completes perfectly fine. So it doesn't seem to be my environment.

**Comment by gardotd426** [comment]
I found it: https://github.com/wine-mirror/wine/commit/437bc14ac352df8b34819f7df6aab0b0fb04dddd

**Comment by AlexxandreFS** [comment]
I have the same problem and I already removed the cache and it still doesn't compile.
The fsync patch was made to work with recent versions of GCC, I'm compiling with GCC 9.3 (buildroot).
Are there any possibilities to make this patch compatible with older versions of GCC?
