### ISSUE TITLE
compiling tkg 5.18.xxx fail

### ISSUE THREAD

**Issue by tuxtergames** [Frogging-Family/wine-tkg-git#156]
Hi,

I'm trying to install this last build in Fedora 32,  but its just fail to finish, I got all dependencies installed and change nothing in customization.cfg, weird that 5.17.xx installed fine here, heres a log and terminal output.

[logs.tar.gz](https://github.com/Frogging-Family/wine-tkg-git/files/5305045/logs.tar.gz)

**Comment by motorailgun** [comment]
Looks like I'm having the same issue. Entire build log: [build.log](https://github.com/Frogging-Family/wine-tkg-git/files/5305211/build.log)
It seems that the exact error happens here:
```
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: bcrypt_main.cross.o:bcrypt_main.c:(.text+0x5caa): undefined reference to `__wine_init_unix_lib'
/usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: bcrypt_main.cross.o:bcrypt_main.c:(.text+0x5ccb): undefined reference to `__wine_init_unix_lib'
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
make[1]: *** [Makefile:356: bcrypt.dll] Error 2
make[1]: *** Waiting for unfinished jobs....
```
I first suspected issue #122 but reverting the commit `fc8a71e` didn't help. I've tried on fresh clone, on Arch Linux.

**Comment by tuxtergames** [comment]
> Looks like I'm having the same issue. Entire build log: [build.log](https://github.com/Frogging-Family/wine-tkg-git/files/5305211/build.log)
> It seems that the exact error happens here:
> 
> ```
> /usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: bcrypt_main.cross.o:bcrypt_main.c:(.text+0x5caa): undefined reference to `__wine_init_unix_lib'
> /usr/lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: bcrypt_main.cross.o:bcrypt_main.c:(.text+0x5ccb): undefined reference to `__wine_init_unix_lib'
> collect2: error: ld returned 1 exit status
> winegcc: /usr/bin/x86_64-w64-mingw32-gcc failed
> make[1]: *** [Makefile:356: bcrypt.dll] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```
> 
> I first suspected issue #122 but reverting the commit `fc8a71e` didn't help. I've tried on fresh clone, on Arch Linux.

I trying in another ntbk here and have the same issue with different hardwate

**Comment by adih2001** [comment]
I am also having the same exact issue here.
