### ISSUE TITLE
Steam client integration doesn't build with gcc 15.1.1

### ISSUE THREAD

**Issue by mikeserv-git** [Frogging-Family/wine-tkg-git#1456]
(well, the winegcc front end with gcc 15 in this case)

This is Valve, not the project, but I'll mention it here. This is a known caveat with gcc 15. I'm not sure how to go about patching this, whether another C standard should be specified or #include <stdbool.h> added. It's something that would have to be patched after it's pulled, near the end of the build.

```
winegcc -m64 -c -Wno-attributes -O2 -I/storage2/shit/build/wine-tkg/wine-tkg-git/proton-tkg/proton_dist_tmp/include/wine -I/storage2/shit/build/wine-tkg/wine-tkg-git/proton-tkg/../wine-tkg-git/src/wine-git/include -I/storage2/shit/build/wine-tkg/wine-tkg-git/proton-tkg/../wine-tkg-git/src/wine-git/include/wine -I. -DSTEAM_API_EXPORTS -Dprivate=public -Dprotected=public  -o winISteamNetworkingFakeUDPPort.o winISteamNetworkingFakeUDPPort.c
In file included from winISteamAppList.c:10:
steam_defs.h:7:14: error: ‘bool’ cannot be defined via ‘typedef’
    7 | typedef char bool; /* 1 byte on modern visual studio c++ */
      |              ^~~~
In file included from winISteamApps.c:10:
steam_defs.h:7:14: error: ‘bool’ cannot be defined via ‘typedef’
    7 | typedef char bool; /* 1 byte on modern visual studio c++ */
```

It would have failed in the vrclient before that for the same reason, but I disabled it (chopped it from proton-tkg.sh seeing as _steamvr_support= in advanced-customization.cfg seems to be ignored (set to true elsewhere?). I have absolutely no use for the vrclient so that would have been acceptable to me, had it been the only occurrence.

**Comment by mikeserv-git** [comment]
This got me through lsteamclient:

```
--- steam_defs.h.orig	2025-05-01 20:50:22.920139225 -0400
+++ steam_defs.h	2025-05-01 20:51:08.150176447 -0400
@@ -1,11 +1,9 @@
 #include <stdint.h>
 #include <limits.h>
+#include <stdbool.h>
 typedef uint32_t EHTMLMouseButton, EHTMLKeyModifiers;
 
 #ifndef __cplusplus
-#ifndef bool
-typedef char bool; /* 1 byte on modern visual studio c++ */
-#endif
 
 typedef uint8_t uint8;
 typedef int8_t int8;
```

I just patched it in function build_lsteamclient in proton-tkg.sh for a test.

It won't actually build without openvr.h though

steam.cpp:62:10: fatal error: openvr.h: No such file or directory

I'll try to fix it. There are 3 instances of vrclient_defs.h trying to do typedef bool

**Comment by mikeserv-git** [comment]
OK then, this. It was actually just one vrclient_defs.h to patch (others were copies)

```
diff -Naur a/external-resources/Proton/lsteamclient/steam_defs.h b/external-resources/Proton/lsteamclient/steam_defs.h
--- a/external-resources/Proton/lsteamclient/steam_defs.h	2025-05-01 21:30:51.000000000 -0400
+++ b/external-resources/Proton/lsteamclient/steam_defs.h	2025-05-01 21:54:16.646361432 -0400
@@ -1,11 +1,9 @@
 #include <stdint.h>
 #include <limits.h>
+#include <stdbool.h>
 typedef uint32_t EHTMLMouseButton, EHTMLKeyModifiers;
 
 #ifndef __cplusplus
-#ifndef bool
-typedef char bool; /* 1 byte on modern visual studio c++ */
-#endif
 
 typedef uint8_t uint8;
 typedef int8_t int8;
diff -Naur a/external-resources/Proton/vrclient_x64/vrclient_x64/vrclient_defs.h b/external-resources/Proton/vrclient_x64/vrclient_x64/vrclient_defs.h
--- a/external-resources/Proton/vrclient_x64/vrclient_x64/vrclient_defs.h	2025-05-01 21:30:51.000000000 -0400
+++ b/external-resources/Proton/vrclient_x64/vrclient_x64/vrclient_defs.h	2025-05-01 21:58:36.854374138 -0400
@@ -1,9 +1,7 @@
 #ifdef __cplusplus
 #include <algorithm>
 #else
-#ifndef bool
-typedef char bool; /* 1 byte on modern visual studio c++ */
-#endif
+#include <stdbool.h>
 
 /* enums */
 typedef int
```

This time I stuck the patch command in function build_vrclient in proton-tkg.sh as that's where in the script that Proton stuff gets pulled in. It's not much fun patching source code you don't have yet.

```
function build_vrclient {
  cd "$_nowhere"
  source "$_nowhere/proton_tkg_token"
  git clone https://github.com/ValveSoftware/openvr.git || true # It'll complain the path already exists on subsequent builds
  cd openvr
  git reset --hard HEAD
  git clean -xdf
  git pull origin master
  #git checkout 52065df3d6f3af96300dac98cdf7397f26abfcd7
  #cd ..

cd "$_nowhere"
patch -Np1 -i steamgcc15bool.patch
cd openvr
```

I got a successful build with gcc 15.1.1
