### ISSUE TITLE
Wine Issue (Unknown)

### ISSUE THREAD

**Issue by IroAlexis** [Frogging-Family/wine-tkg-git#177]
Hi TkG,

Since Wednesday, it is impossible for me to launch applications that ask to display a Windows interface such as the login window Riot and Minecraft Dungeons Launcher. I get an empty gray window as you can see
![Screenshot from 2020-10-09 23-27-27](https://user-images.githubusercontent.com/48684344/95666653-fd07ac00-0b5b-11eb-8b7a-e9d814700243.png)

In the Wine log with DXVK, I have this errror with the both `040c:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x100b4`.
Without DXVK, I have this logs : [riot-wine.log](https://github.com/Frogging-Family/wine-tkg-git/files/5360394/riot-wine.log) & [minecraft-dungeons-launcher-wine.log](https://github.com/Frogging-Family/wine-tkg-git/files/5360395/minecraft-dungeons-launcher-wine.log)

At the moment, I don't see who's causing this. I think I can rule out problems with my installation :
* Kernel: 5.8.14-22-tkg-pds
* DE: GNOME 3.38.1
* GPU: NVIDIA GeForce GTX 1070
* Driver: 455.26.01 (Vulkan Dev)
* Wine TkG Config: [customization.cfg](https://github.com/Frogging-Family/wine-tkg-git/files/5360401/customization.log)

I can give more information if this issue is not complete enough.

Edit : It works perfectly with Wine Staging 5.18, but I need recerate the prefix else I have same results. Just for precision, everything works perfectly when there is no need for a Windows interface (The Witcher 3, Control,...)

Edit 2 : Uplay and GOG Installer are not affected and EGS is affected according to users

**Comment by IroAlexis** [comment]
Today, I compile with default `customization.cfg` and same results.

After more "tests", I noted this :
 * With the commit https://github.com/Frogging-Family/wine-tkg-git/commit/b5b05171556f1b64f5ccca5587cc56b73ad022ca, it works perfectly. Just for test, I use this wine staging commit (https://github.com/wine-staging/wine-staging/commit/194669052e1bce63659f1fbb0880da3dcb03058e) in actual master and unfortunately the compilation failed (in coming error file)
* With the commit https://github.com/Frogging-Family/wine-tkg-git/commit/9a56f989c99967abc4ea90a1a393307643c06cfe, I reproduce my issue.

**Comment by IroAlexis** [comment]
Ah ok my bad, it is a regression on the side of Wine Staging 5.19...
